name: Lint
# https://github.com/psf/black/blob/main/action.yml

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: "3.11"
      - uses: psf/black@stable
